version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    steps:
        - checkout
        - run:
            name: Tests runner
            working_directory: swcregistrypython/
            command: |
              pip install -r requirements.txt
              cd swcregistrypython
              python swcregistrypython/test.py
